In [1]:
import numpy as np

CREATING

In [2]:
x1 = np.array([1,2,3,4,])
print(x1)
print(x1.shape)
print(x1.ndim)
print(type(x1))

[1 2 3 4]
(4,)
1
<class 'numpy.ndarray'>


In [5]:
x2 = np.array([    
    [1,2,3],
    [4,5,6]
])
print(x2)
print(x2.shape)
print(x2.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3)
2


In [7]:
a = np.arange(10 ,51,)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [8]:
b = np.linspace(10,15,25)
print(b)

[10.         10.20833333 10.41666667 10.625      10.83333333 11.04166667
 11.25       11.45833333 11.66666667 11.875      12.08333333 12.29166667
 12.5        12.70833333 12.91666667 13.125      13.33333333 13.54166667
 13.75       13.95833333 14.16666667 14.375      14.58333333 14.79166667
 15.        ]


In [9]:
c = np.random.randint(-10,10,(5,5))
print(c)

[[  6   0  -2  -4  -2]
 [  7   1  -4  -6  -9]
 [ -7   1  -8 -10   3]
 [  3  -6  -7  -1  -4]
 [  5  -6  -5   4   3]]
